//! Inspect a tuning binary output file.
//!
//! This example reads a .bin file generated by the LocalBackend's tuning output
//! feature and displays the conversation with token-level probability information.
//!
//! Usage:
//!   cargo run --example inspect_tuning -- <path-to-tuning.bin> [--tokenizer <repo>]
//!
//! Example:
//!   cargo run --example inspect_tuning -- ~/.paramecia/generations/abc123.bin

use std::fs::File;
use std::io::Read;
use std::path::PathBuf;

use anyhow::{bail, Context, Result};
use bytemuck::{Pod, Zeroable};
use half::f16;
use hf_hub::api::sync::Api;
use tokenizers::Tokenizer;

/// Magic bytes for tuning output files.
const TUNING_MAGIC: [u8; 4] = *b"PGEN";

/// Header for tuning output files (32 bytes).
#[repr(C, packed)]
#[derive(Debug, Clone, Copy, Pod, Zeroable)]
struct TuningHeader {
    magic: [u8; 4],
    version: u16,
    n_top_k: u16,
    n_tail: u16,
    n_tokens: u32,
    n_assistant_tokens: u32,
    vocab_size: u32,
    n_layers: u16,
    n_experts_per_tok: u8,
    reserved: [u8; 7],
}

impl TuningHeader {
    fn has_expert_data(&self) -> bool {
        self.version >= 2 && self.n_layers > 0 && self.n_experts_per_tok > 0
    }

    fn expert_indices_per_token(&self) -> usize {
        self.n_layers as usize * self.n_experts_per_tok as usize
    }
}

/// Single logit entry (6 bytes).
#[repr(C, packed)]
#[derive(Debug, Clone, Copy, Pod, Zeroable)]
struct LogitEntry {
    token_id: u32,
    log_prob_bits: u16,
}

impl LogitEntry {
    fn log_prob(&self) -> f32 {
        f16::from_bits(self.log_prob_bits).to_f32()
    }

    fn prob(&self) -> f32 {
        self.log_prob().exp()
    }
}

/// Parsed tuning data for a single assistant token position.
struct AssistantTokenData {
    token_id: u32,
    top_k: Vec<LogitEntry>,
    tail: Vec<LogitEntry>,
    #[allow(dead_code)]
    tail_mass: f32,
    /// Expert indices for this token, shape [n_layers * n_experts_per_tok]
    expert_indices: Vec<u32>,
}

/// Full parsed tuning file.
struct TuningData {
    header: TuningHeader,
    token_ids: Vec<u32>,
    assistant_mask: Vec<u8>,
    assistant_data: Vec<AssistantTokenData>,
}

fn parse_tuning_file(path: &PathBuf) -> Result<TuningData> {
    let mut file = File::open(path).context("Failed to open tuning file")?;
    let mut data = Vec::new();
    file.read_to_end(&mut data)?;

    // Parse header
    if data.len() < 32 {
        bail!("File too small for header");
    }
    let header: TuningHeader = *bytemuck::from_bytes(&data[0..32]);

    if header.magic != TUNING_MAGIC {
        bail!(
            "Invalid magic bytes: expected {:?}, got {:?}",
            TUNING_MAGIC,
            header.magic
        );
    }

    let n_tokens = header.n_tokens as usize;
    let n_assistant = header.n_assistant_tokens as usize;
    let n_top_k = header.n_top_k as usize;
    let n_tail = header.n_tail as usize;
    let entries_per_token = n_top_k + n_tail;

    // Calculate expected file size
    let token_ids_size = n_tokens * 4;
    let mask_size = n_tokens;
    let logits_size = n_assistant * entries_per_token * 6; // 6 bytes per LogitEntry
    let tail_mass_size = n_assistant * 2; // f16 per assistant token
    let version = header.version;
    let bytes_per_expert_index: usize = if version >= 3 { 2 } else { 1 };
    let expert_indices_size = if header.has_expert_data() {
        n_assistant * header.expert_indices_per_token() * bytes_per_expert_index
    } else {
        0
    };
    let expected_size =
        32 + token_ids_size + mask_size + logits_size + tail_mass_size + expert_indices_size;

    if data.len() < expected_size {
        bail!(
            "File too small: expected {} bytes, got {}",
            expected_size,
            data.len()
        );
    }

    // Parse token IDs
    let token_ids_start = 32;
    let token_ids_end = token_ids_start + token_ids_size;
    let token_ids: Vec<u32> = bytemuck::cast_slice(&data[token_ids_start..token_ids_end]).to_vec();

    // Parse assistant mask
    let mask_start = token_ids_end;
    let mask_end = mask_start + mask_size;
    let assistant_mask = data[mask_start..mask_end].to_vec();

    // Parse logit data for each assistant token
    let logits_start = mask_end;
    let tail_mass_start = logits_start + n_assistant * entries_per_token * 6;
    let expert_indices_start = tail_mass_start + tail_mass_size;

    let mut assistant_data = Vec::with_capacity(n_assistant);

    // Find which token positions are assistant tokens
    let assistant_positions: Vec<usize> = assistant_mask
        .iter()
        .enumerate()
        .filter_map(|(i, &m)| if m == 1 { Some(i) } else { None })
        .collect();

    for (i, &pos) in assistant_positions.iter().enumerate() {
        let entry_start = logits_start + i * entries_per_token * 6;

        // Parse top-k entries
        let top_k_bytes = &data[entry_start..entry_start + n_top_k * 6];
        let top_k: Vec<LogitEntry> = bytemuck::cast_slice(top_k_bytes).to_vec();

        // Parse tail entries
        let tail_start = entry_start + n_top_k * 6;
        let tail_bytes = &data[tail_start..tail_start + n_tail * 6];
        let tail: Vec<LogitEntry> = bytemuck::cast_slice(tail_bytes).to_vec();

        // Parse tail mass
        let tail_mass_offset = tail_mass_start + i * 2;
        let tail_mass_bits =
            u16::from_le_bytes([data[tail_mass_offset], data[tail_mass_offset + 1]]);
        let tail_mass = f16::from_bits(tail_mass_bits).to_f32();

        // Parse expert indices if present
        let expert_indices: Vec<u32> = if header.has_expert_data() {
            let indices_per_token = header.expert_indices_per_token();
            let byte_len = indices_per_token * bytes_per_expert_index;
            let expert_offset = expert_indices_start + i * byte_len;
            let raw = &data[expert_offset..expert_offset + byte_len];
            if version >= 3 {
                raw.chunks_exact(2)
                    .map(|c| u16::from_le_bytes([c[0], c[1]]) as u32)
                    .collect()
            } else {
                raw.iter().map(|&b| b as u32).collect()
            }
        } else {
            Vec::new()
        };

        assistant_data.push(AssistantTokenData {
            token_id: token_ids[pos],
            top_k,
            tail,
            tail_mass,
            expert_indices,
        });
    }

    Ok(TuningData {
        header,
        token_ids,
        assistant_mask,
        assistant_data,
    })
}

fn print_header(header: &TuningHeader) {
    // Copy packed fields to avoid unaligned reference issues
    let version = header.version;
    let n_top_k = header.n_top_k;
    let n_tail = header.n_tail;
    let n_tokens = header.n_tokens;
    let n_assistant_tokens = header.n_assistant_tokens;
    let vocab_size = header.vocab_size;
    let n_layers = header.n_layers;
    let n_experts_per_tok = header.n_experts_per_tok;

    println!("=== Tuning File Header ===");
    println!(
        "Magic:              {:?}",
        std::str::from_utf8(&header.magic).unwrap_or("???")
    );
    println!("Version:            {}", version);
    println!("Top-K per token:    {}", n_top_k);
    println!("Tail samples:       {}", n_tail);
    println!("Total tokens:       {}", n_tokens);
    println!("Assistant tokens:   {}", n_assistant_tokens);
    println!("Vocab size:         {}", vocab_size);
    if header.has_expert_data() {
        println!("MoE layers:         {}", n_layers);
        println!("Experts per token:  {}", n_experts_per_tok);
    }
    println!();
}

/// Format a token for display, showing token ID if it contains replacement chars
fn format_token_display(tokenizer: &Tokenizer, token_id: u32) -> String {
    let text = tokenizer
        .decode(&[token_id], false)
        .unwrap_or_else(|_| format!("<{}>", token_id));

    // If the text contains replacement characters (partial UTF-8), show the token ID
    if text.contains('\u{FFFD}') {
        format!("<tok:{}>", token_id)
    } else {
        text.replace('\n', "\\n")
            .replace('\r', "\\r")
            .replace('\t', "\\t")
    }
}

/// Format a probability as a percentage, using scientific notation only for very small values.
fn format_prob(prob: f32) -> String {
    let pct = prob * 100.0;
    if pct >= 0.1 {
        // Normal decimal notation for readable values
        format!("{:.1}%", pct)
    } else if pct > 0.0 {
        // Scientific notation for values < 0.1%
        format!("{:.1e}%", pct)
    } else {
        "0%".to_string()
    }
}

/// Format expert routing info showing most frequent expert and count of unique experts.
/// Returns something like "E42 (5 unique)" meaning expert 42 was used most frequently
/// and 5 unique experts were used total across all layers.
fn format_expert_info(expert_indices: &[u32]) -> String {
    if expert_indices.is_empty() {
        return String::new();
    }

    // Count occurrences of each expert
    let mut counts = std::collections::HashMap::new();
    for &expert in expert_indices {
        *counts.entry(expert).or_insert(0usize) += 1;
    }

    // Find most frequent expert
    let (most_frequent, max_count) = counts
        .iter()
        .max_by_key(|(_, &count)| count)
        .map(|(&expert, &count)| (expert, count))
        .unwrap_or((0, 0));

    let unique_count = counts.len();

    if unique_count == 1 {
        // All same expert
        format!(" E{}", most_frequent)
    } else {
        // Show most frequent expert and count of unique experts
        format!(" E{}x{}/{}", most_frequent, max_count, unique_count)
    }
}

fn format_token_with_predictions(
    tokenizer: &Tokenizer,
    token_id: u32,
    top_k: &[LogitEntry],
    tail: &[LogitEntry],
    expert_indices: &[u32],
) -> String {
    let token_display = format_token_display(tokenizer, token_id);
    let expert_info = format_expert_info(expert_indices);

    // Get valid top-k entries (non-padding)
    let valid_top_k: Vec<&LogitEntry> = top_k
        .iter()
        .filter(|e| e.log_prob() > f32::NEG_INFINITY)
        .collect();

    // Get valid tail entries (non-padding)
    let valid_tail: Vec<&LogitEntry> = tail
        .iter()
        .filter(|e| e.log_prob() > f32::NEG_INFINITY)
        .collect();

    if valid_top_k.is_empty() {
        return format!("{} [no predictions]{}", token_display, expert_info);
    }

    // Format top 2 predictions
    let top_2: Vec<String> = valid_top_k
        .iter()
        .take(2)
        .map(|e| {
            let tid = e.token_id;
            let text = format_token_display(tokenizer, tid);
            format!("\"{}\" ({})", text, format_prob(e.prob()))
        })
        .collect();

    // Remaining top-k count (excluding top 2)
    let remaining_top_k = valid_top_k.len().saturating_sub(2);

    // Format one tail entry if available
    let tail_sample = valid_tail.first().map(|e| {
        let tid = e.token_id;
        let text = format_token_display(tokenizer, tid);
        format!("\"{}\" ({})", text, format_prob(e.prob()))
    });
    let remaining_tail = valid_tail
        .len()
        .saturating_sub(if tail_sample.is_some() { 1 } else { 0 });

    // Build output (expert info at the end)
    match (remaining_top_k, tail_sample) {
        (0, None) => {
            format!("{} [{}]{}", token_display, top_2.join(", "), expert_info)
        }
        (0, Some(ts)) => {
            format!(
                "{} [{}, {}, +{} tail]{}",
                token_display,
                top_2.join(", "),
                ts,
                remaining_tail,
                expert_info
            )
        }
        (n, None) => {
            format!(
                "{} [{}, +{} top-k]{}",
                token_display,
                top_2.join(", "),
                n,
                expert_info
            )
        }
        (n, Some(ts)) => {
            format!(
                "{} [{}, .. +{} top-k .., {}, +{} tail]{}",
                token_display,
                top_2.join(", "),
                n,
                ts,
                remaining_tail,
                expert_info
            )
        }
    }
}

/// Represents a segment of the conversation (either prompt text or generated tokens).
enum ConversationSegment {
    /// Non-assistant tokens that form a prompt/context message
    Prompt(Vec<u32>),
    /// Assistant-generated tokens with their prediction data indices
    Generated(Vec<usize>), // indices into assistant_data
}

fn print_conversation(tokenizer: &Tokenizer, data: &TuningData) {
    println!("=== Conversation ===\n");

    // Group consecutive tokens by their mask value
    let mut segments: Vec<ConversationSegment> = Vec::new();
    let mut current_prompt_tokens: Vec<u32> = Vec::new();
    let mut current_generated_indices: Vec<usize> = Vec::new();
    let mut assistant_data_idx = 0;

    for (&token_id, &mask) in data.token_ids.iter().zip(data.assistant_mask.iter()) {
        if mask == 0 {
            // Non-assistant token
            if !current_generated_indices.is_empty() {
                segments.push(ConversationSegment::Generated(std::mem::take(
                    &mut current_generated_indices,
                )));
            }
            current_prompt_tokens.push(token_id);
        } else {
            // Assistant token
            if !current_prompt_tokens.is_empty() {
                segments.push(ConversationSegment::Prompt(std::mem::take(
                    &mut current_prompt_tokens,
                )));
            }
            current_generated_indices.push(assistant_data_idx);
            assistant_data_idx += 1;
        }
    }

    // Don't forget the last segment
    if !current_prompt_tokens.is_empty() {
        segments.push(ConversationSegment::Prompt(current_prompt_tokens));
    }
    if !current_generated_indices.is_empty() {
        segments.push(ConversationSegment::Generated(current_generated_indices));
    }

    // Print each segment
    let mut response_number = 1;
    for segment in &segments {
        match segment {
            ConversationSegment::Prompt(tokens) => {
                let text = tokenizer
                    .decode(tokens, false)
                    .unwrap_or_else(|_| "<decode error>".to_string());

                // Parse ChatML format to extract messages
                let parts: Vec<&str> = text.split("<|im_start|>").collect();
                for part in parts.iter().skip(1) {
                    let part = part.trim();
                    if part.is_empty() {
                        continue;
                    }

                    if let Some(newline_pos) = part.find('\n') {
                        let role = &part[..newline_pos];
                        let content = part[newline_pos + 1..]
                            .replace("<|im_end|>", "")
                            .trim()
                            .to_string();

                        if !content.is_empty() {
                            // Check if this is a tool result (role starts with "tool[")
                            if role.starts_with("tool[") {
                                // Extract tool name from role like "tool[read_file:call_123]"
                                let tool_info =
                                    role.trim_start_matches("tool[").trim_end_matches(']');
                                let tool_name = tool_info.split(':').next().unwrap_or("unknown");
                                println!("--- Tool Result ({}) ---", tool_name);
                                // Truncate very long tool results for readability
                                if content.len() > 500 {
                                    println!(
                                        "{}...\n[truncated, {} chars total]\n",
                                        &content[..500],
                                        content.len()
                                    );
                                } else {
                                    println!("{}\n", content);
                                }
                            } else if content.contains("<tool_response>") {
                                // Alternative format: user message with <tool_response> tag
                                let tool_content = content
                                    .replace("<tool_response>", "")
                                    .replace("</tool_response>", "")
                                    .trim()
                                    .to_string();
                                println!("--- Tool Result ---");
                                if tool_content.len() > 500 {
                                    println!(
                                        "{}...\n[truncated, {} chars total]\n",
                                        &tool_content[..500],
                                        tool_content.len()
                                    );
                                } else {
                                    println!("{}\n", tool_content);
                                }
                            } else {
                                let role_label = match role {
                                    "user" => "User",
                                    "assistant" => "Assistant",
                                    "system" => "System",
                                    _ => role,
                                };
                                println!("--- {} ---", role_label);
                                println!("{}\n", content);
                            }
                        }
                    }
                }
            }
            ConversationSegment::Generated(indices) => {
                println!("--- Generated Response {} ---", response_number);
                response_number += 1;
                for (local_idx, &data_idx) in indices.iter().enumerate() {
                    let ad = &data.assistant_data[data_idx];
                    let formatted = format_token_with_predictions(
                        tokenizer,
                        ad.token_id,
                        &ad.top_k,
                        &ad.tail,
                        &ad.expert_indices,
                    );
                    println!("{:4}: {}", local_idx, formatted);
                }
                println!();
            }
        }
    }
}

fn main() -> Result<()> {
    let args: Vec<String> = std::env::args().collect();

    if args.len() < 2 {
        eprintln!("Usage: {} <tuning.bin> [--tokenizer <repo>]", args[0]);
        eprintln!();
        eprintln!("Example:");
        eprintln!("  {} ~/.paramecia/generations/abc123.bin", args[0]);
        std::process::exit(1);
    }

    let tuning_path = PathBuf::from(&args[1]);

    // Parse tokenizer repo from args
    let tokenizer_repo = args
        .iter()
        .position(|a| a == "--tokenizer")
        .and_then(|i| args.get(i + 1))
        .map(|s| s.as_str())
        .unwrap_or("Qwen/Qwen3-Next-80B-A3B-Instruct");

    println!("Loading tokenizer from {}...", tokenizer_repo);
    let api = Api::new()?;
    let repo = api.model(tokenizer_repo.to_string());
    let tokenizer_path = repo.get("tokenizer.json")?;
    let tokenizer = Tokenizer::from_file(&tokenizer_path)
        .map_err(|e| anyhow::anyhow!("Failed to load tokenizer: {}", e))?;

    println!("Parsing tuning file: {}", tuning_path.display());
    let data = parse_tuning_file(&tuning_path)?;

    println!();
    print_header(&data.header);
    print_conversation(&tokenizer, &data);

    Ok(())
}
