[package]
name = "paramecia-visualizer"
description = "Model visualizer for paramecia"
version = "0.1.0"
authors = ["Nick Senger"]
edition = "2024"
publish = false

[dependencies]
fastrand = "2"
iced = { version = "0.13", features = ["tokio"] }
iced-sugiyama = { path = "../../iced-sugiyama", features = ["animated"] }
paramecia-arrow = { workspace = true }
paramecia-model = { workspace = true }
